# Generated by Django 3.2.5 on 2021-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='play',
            name='description2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='description3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
