# Generated by Django 3.2.5 on 2021-09-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210905_1510'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courtlocation',
            unique_together={('x', 'y')},
        ),
        migrations.AlterUniqueTogether(
            name='lineup',
            unique_together={('player1', 'player2', 'player3', 'player4', 'player5')},
        ),
        migrations.AlterUniqueTogether(
            name='playerseason',
            unique_together={('player', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('year', 'season_type')},
        ),
        migrations.AlterUniqueTogether(
            name='teamseason',
            unique_together={('team', 'season')},
        ),
    ]
