# Generated by Django 3.2.5 on 2021-09-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210905_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='primary_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_team', to='app.teamseason'),
        ),
    ]
